name: pyscreener

channels:
  - conda-forge
  - defaults

dependencies:
  - pdbfixer
  - pip
  - python=3.8
  - openbabel
  - openmm
  - pip:
    - colorama
    - configargparse
    - h5py
    - numpy
    - ray[default]>=2.0
    - rdkit
    - pandas
    - scikit_learn
    - scipy
    - tqdm
